### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by Aman9das** [vinceliuice/Graphite-cursors#3]
The icons are X11 cursors, are there plans for future wayland support?

**Comment by vinceliuice** [comment]
Just run `sudo ./install.sh`

**Comment by Aman9das** [comment]
Alright see the Environment variable section of https://wiki.archlinux.org/title/Cursor_themes

I guess we should integrate it to install.sh

**Comment by vinceliuice** [comment]
How? I don't know how to do with this

**Comment by Aman9das** [comment]
I have made a rough pull request to suggest the idea :)

>Note: By default, on Wayland, Gnome applications should be unable to display your cursor themes located in ~/.local/share/icons. As a workaround, you can add that path to XCURSOR_PATH.
